const db = require("./lib/db");

const init = async () => {
  const partnerLevels = await db.partnerLevel.find();
  if (!partnerLevels.length) {
    console.log("No partner levels found, creating default ones...");
    await db.partnerLevel.insertMany([
      { name: "A", price: 75.2 },
      { name: "B", price: 37.6 },
      { name: "C", price: 18.8 },
      { name: "D", price: 9.4 },
      { name: "E", price: 1.9 },
      { name: "F", price: 1.4 },
    ]);
  }

  const regions = await db.region.find();
  if (!regions.length) {
    console.log("No regions found, creating default ones...");
    await db.region.insertMany([
      {
        index: 1,
        name: "Arica y Parinacota",
        romanNumber: "XV",
        number: 15,
        abbreviation: "AP",
      },
      {
        index: 2,
        name: "Tarapacá",
        romanNumber: "I",
        number: 1,
        abbreviation: "TA",
      },
      {
        index: 3,
        name: "Antofagasta",
        romanNumber: "II",
        number: 2,
        abbreviation: "AN",
      },
      {
        index: 4,
        name: "Atacama",
        romanNumber: "III",
        number: 3,
        abbreviation: "AT",
      },
      {
        index: 5,
        name: "Coquimbo",
        romanNumber: "IV",
        number: 4,
        abbreviation: "CO",
      },
      {
        index: 6,
        name: "Valparaíso",
        romanNumber: "V",
        number: 5,
        abbreviation: "VA",
      },
      {
        index: 7,
        name: "Metropolitana de Santiago",
        romanNumber: "XIII",
        number: 13,
        abbreviation: "RM",
      },
      {
        index: 8,
        name: "Libertador General Bernardo O'Higgins",
        romanNumber: "VI",
        number: 6,
        abbreviation: "LI",
      },
      {
        index: 9,
        name: "Maule",
        romanNumber: "VII",
        number: 7,
        abbreviation: "ML",
      },
      {
        index: 10,
        name: "Ñuble",
        romanNumber: "XVI",
        number: 16,
        abbreviation: "NB",
      },
      {
        index: 11,
        name: "Biobío",
        romanNumber: "VIII",
        number: 8,
        abbreviation: "BI",
      },
      {
        index: 12,
        name: "La Araucanía",
        romanNumber: "IX",
        number: 9,
        abbreviation: "AR",
      },
      {
        index: 13,
        name: "Los Ríos",
        romanNumber: "XIV",
        number: 14,
        abbreviation: "LR",
      },
      {
        index: 14,
        name: "Los Lagos",
        romanNumber: "X",
        number: 10,
        abbreviation: "LL",
      },
      {
        index: 15,
        name: "Aysén del General Carlos Ibáñez del Campo",
        romanNumber: "XI",
        number: 11,
        abbreviation: "AI",
      },
      {
        index: 16,
        name: "Magallanes y de la Antártica Chilena",
        romanNumber: "XII",
        number: 12,
        abbreviation: "MA",
      },
    ]);
  }

  const communes = await db.commune.find();
  if (!communes.length) {
    console.log("No communes found, creating default ones...");
    const storedRegions = await db.region.find();
    const reg15 = storedRegions.find((r) => r.number === 15);
    await db.commune.insertMany([
      { name: "Arica", regionId: reg15._id },
      { name: "Camarones", regionId: reg15._id },
      { name: "General Lagos", regionId: reg15._id },
      { name: "Putre", regionId: reg15._id },
    ]);
    const reg1 = storedRegions.find((r) => r.number === 1);
    await db.commune.insertMany([
      { name: "Alto Hospicio", regionId: reg1._id },
      { name: "Camiña", regionId: reg1._id },
      { name: "Colchane", regionId: reg1._id },
      { name: "Huara", regionId: reg1._id },
      { name: "Iquique", regionId: reg1._id },
      { name: "Pica", regionId: reg1._id },
      { name: "Pozo Almonte", regionId: reg1._id },
    ]);
    const reg2 = storedRegions.find((r) => r.number === 2);
    await db.commune.insertMany([
      { name: "Antofagasta", regionId: reg2._id },
      { name: "Calama", regionId: reg2._id },
      { name: "María Elena", regionId: reg2._id },
      { name: "Mejillones", regionId: reg2._id },
      { name: "Ollagüe", regionId: reg2._id },
      { name: "San Pedro de Atacama", regionId: reg2._id },
      { name: "Sierra Gorda", regionId: reg2._id },
      { name: "Taltal", regionId: reg2._id },
      { name: "Tocopilla", regionId: reg2._id },
    ]);
    const reg3 = storedRegions.find((r) => r.number === 3);
    await db.commune.insertMany([
      { name: "Alto del Carmen", regionId: reg3._id },
      { name: "Caldera", regionId: reg3._id },
      { name: "Chañaral", regionId: reg3._id },
      { name: "Copiapó", regionId: reg3._id },
      { name: "Diego de Almagro", regionId: reg3._id },
      { name: "Freirina", regionId: reg3._id },
      { name: "Huasco", regionId: reg3._id },
      { name: "Tierra Amarilla", regionId: reg3._id },
      { name: "Vallenar", regionId: reg3._id },
    ]);
    const reg4 = storedRegions.find((r) => r.number === 4);
    await db.commune.insertMany([
      { name: "Andacollo", regionId: reg4._id },
      { name: "Canela", regionId: reg4._id },
      { name: "Combarbalá", regionId: reg4._id },
      { name: "Coquimbo", regionId: reg4._id },
      { name: "Illapel", regionId: reg4._id },
      { name: "La Higuera", regionId: reg4._id },
      { name: "La Serena", regionId: reg4._id },
      { name: "Los Vilos", regionId: reg4._id },
      { name: "Monte Patria", regionId: reg4._id },
      { name: "Ovalle", regionId: reg4._id },
      { name: "Paiguano", regionId: reg4._id },
      { name: "Punitaqui", regionId: reg4._id },
      { name: "Río Hurtado", regionId: reg4._id },
      { name: "Salamanca", regionId: reg4._id },
      { name: "Vicuña", regionId: reg4._id },
    ]);
    const reg5 = storedRegions.find((r) => r.number === 5);
    await db.commune.insertMany([
      { name: "Algarrobo", regionId: reg5._id },
      { name: "Cabildo", regionId: reg5._id },
      { name: "Calera", regionId: reg5._id },
      { name: "Calle Larga", regionId: reg5._id },
      { name: "Cartagena", regionId: reg5._id },
      { name: "Casablanca", regionId: reg5._id },
      { name: "Catemu", regionId: reg5._id },
      { name: "Concón", regionId: reg5._id },
      { name: "El Quisco", regionId: reg5._id },
      { name: "El Tabo", regionId: reg5._id },
      { name: "Hijuelas", regionId: reg5._id },
      { name: "Isla de Pascua", regionId: reg5._id },
      { name: "Juan Fernández", regionId: reg5._id },
      { name: "La Cruz", regionId: reg5._id },
      { name: "La Ligua", regionId: reg5._id },
      { name: "Limache", regionId: reg5._id },
      { name: "Llaillay", regionId: reg5._id },
      { name: "Los Andes", regionId: reg5._id },
      { name: "Nogales", regionId: reg5._id },
      { name: "Olmué", regionId: reg5._id },
      { name: "Panquehue", regionId: reg5._id },
      { name: "Papudo", regionId: reg5._id },
      { name: "Petorca", regionId: reg5._id },
      { name: "Puchuncaví", regionId: reg5._id },
      { name: "Putaendo", regionId: reg5._id },
      { name: "Quillota", regionId: reg5._id },
      { name: "Quilpué", regionId: reg5._id },
      { name: "Quintero", regionId: reg5._id },
      { name: "Rinconada", regionId: reg5._id },
      { name: "San Antonio", regionId: reg5._id },
      { name: "San Esteban", regionId: reg5._id },
      { name: "San Felipe", regionId: reg5._id },
      { name: "Santa María", regionId: reg5._id },
      { name: "Santo Domingo", regionId: reg5._id },
      { name: "Valparaíso", regionId: reg5._id },
      { name: "Villa Alemana", regionId: reg5._id },
      { name: "Viña del Mar", regionId: reg5._id },
      { name: "Zapallar", regionId: reg5._id },
    ]);
    const reg13 = storedRegions.find((r) => r.number === 13);
    await db.commune.insertMany([
      { name: "Alhué", regionId: reg13._id },
      { name: "Buin", regionId: reg13._id },
      { name: "Calera de Tango", regionId: reg13._id },
      { name: "Cerrillos", regionId: reg13._id },
      { name: "Cerro Navia", regionId: reg13._id },
      { name: "Colina", regionId: reg13._id },
      { name: "Conchalí", regionId: reg13._id },
      { name: "Curacaví", regionId: reg13._id },
      { name: "El Bosque", regionId: reg13._id },
      { name: "El Monte", regionId: reg13._id },
      { name: "Estación Central", regionId: reg13._id },
      { name: "Huechuraba", regionId: reg13._id },
      { name: "Independencia", regionId: reg13._id },
      { name: "Isla de Maipo", regionId: reg13._id },
      { name: "La Cisterna", regionId: reg13._id },
      { name: "La Florida", regionId: reg13._id },
      { name: "La Granja", regionId: reg13._id },
      { name: "La Pintana", regionId: reg13._id },
      { name: "La Reina", regionId: reg13._id },
      { name: "Lampa", regionId: reg13._id },
      { name: "Las Condes", regionId: reg13._id },
      { name: "Lo Barnechea", regionId: reg13._id },
      { name: "Lo Espejo", regionId: reg13._id },
      { name: "Lo Prado", regionId: reg13._id },
      { name: "Macul", regionId: reg13._id },
      { name: "Maipú", regionId: reg13._id },
      { name: "María Pinto", regionId: reg13._id },
      { name: "Melipilla", regionId: reg13._id },
      { name: "Ñuñoa", regionId: reg13._id },
      { name: "Padre Hurtado", regionId: reg13._id },
      { name: "Paine", regionId: reg13._id },
      { name: "Pedro Aguirre Cerda", regionId: reg13._id },
      { name: "Peñaflor", regionId: reg13._id },
      { name: "Peñalolén", regionId: reg13._id },
      { name: "Pirque", regionId: reg13._id },
      { name: "Providencia", regionId: reg13._id },
      { name: "Pudahuel", regionId: reg13._id },
      { name: "Puente Alto", regionId: reg13._id },
      { name: "Quilicura", regionId: reg13._id },
      { name: "Quinta Normal", regionId: reg13._id },
      { name: "Recoleta", regionId: reg13._id },
      { name: "Renca", regionId: reg13._id },
      { name: "San Bernardo", regionId: reg13._id },
      { name: "San Joaquín", regionId: reg13._id },
      { name: "San José de Maipo", regionId: reg13._id },
      { name: "San Miguel", regionId: reg13._id },
      { name: "San Pedro", regionId: reg13._id },
      { name: "San Ramón", regionId: reg13._id },
      { name: "Santiago", regionId: reg13._id },
      { name: "Talagante", regionId: reg13._id },
      { name: "Tiltil", regionId: reg13._id },
      { name: "Vitacura", regionId: reg13._id },
    ]);
    const reg6 = storedRegions.find((r) => r.number === 6);
    await db.commune.insertMany([
      { name: "Chimbarongo", regionId: reg6._id },
      { name: "Chépica", regionId: reg6._id },
      { name: "Codegua", regionId: reg6._id },
      { name: "Coinco", regionId: reg6._id },
      { name: "Coltauco", regionId: reg6._id },
      { name: "Doñihue", regionId: reg6._id },
      { name: "Graneros", regionId: reg6._id },
      { name: "La Estrella", regionId: reg6._id },
      { name: "Las Cabras", regionId: reg6._id },
      { name: "Litueche", regionId: reg6._id },
      { name: "Lolol", regionId: reg6._id },
      { name: "Machalí", regionId: reg6._id },
      { name: "Malloa", regionId: reg6._id },
      { name: "Marchihue", regionId: reg6._id },
      { name: "Nancagua", regionId: reg6._id },
      { name: "Navidad", regionId: reg6._id },
      { name: "Olivar", regionId: reg6._id },
      { name: "Palmilla", regionId: reg6._id },
      { name: "Paredones", regionId: reg6._id },
      { name: "Peralillo", regionId: reg6._id },
      { name: "Peumo", regionId: reg6._id },
      { name: "Pichidegua", regionId: reg6._id },
      { name: "Pichilemu", regionId: reg6._id },
      { name: "Placilla", regionId: reg6._id },
      { name: "Pumanque", regionId: reg6._id },
      { name: "Quinta de Tilcoco", regionId: reg6._id },
      { name: "Rancagua", regionId: reg6._id },
      { name: "Rengo", regionId: reg6._id },
      { name: "Requínoa", regionId: reg6._id },
      { name: "San Fernando", regionId: reg6._id },
      { name: "San Francisco de Mostazal", regionId: reg6._id },
      { name: "San Vicente de Tagua Tagua", regionId: reg6._id },
      { name: "Santa Cruz", regionId: reg6._id },
    ]);
    const reg7 = storedRegions.find((r) => r.number === 7);
    await db.commune.insertMany([
      { name: "Cauquenes", regionId: reg7._id },
      { name: "Chanco", regionId: reg7._id },
      { name: "Colbún", regionId: reg7._id },
      { name: "Constitución", regionId: reg7._id },
      { name: "Curepto", regionId: reg7._id },
      { name: "Curicó", regionId: reg7._id },
      { name: "Empedrado", regionId: reg7._id },
      { name: "Hualañé", regionId: reg7._id },
      { name: "Licantén", regionId: reg7._id },
      { name: "Linares", regionId: reg7._id },
      { name: "Longaví", regionId: reg7._id },
      { name: "Maule", regionId: reg7._id },
      { name: "Molina", regionId: reg7._id },
      { name: "Parral", regionId: reg7._id },
      { name: "Pelarco", regionId: reg7._id },
      { name: "Pelluhue", regionId: reg7._id },
      { name: "Pencahue", regionId: reg7._id },
      { name: "Rauco", regionId: reg7._id },
      { name: "Retiro", regionId: reg7._id },
      { name: "Romeral", regionId: reg7._id },
      { name: "Río Claro", regionId: reg7._id },
      { name: "Sagrada Familia", regionId: reg7._id },
      { name: "San Clemente", regionId: reg7._id },
      { name: "San Javier de Loncomilla", regionId: reg7._id },
      { name: "San Rafael", regionId: reg7._id },
      { name: "Talca", regionId: reg7._id },
      { name: "Teno", regionId: reg7._id },
      { name: "Vichuquén", regionId: reg7._id },
      { name: "Villa Alegre", regionId: reg7._id },
      { name: "Yerbas Buenas", regionId: reg7._id },
    ]);
    const reg16 = storedRegions.find((r) => r.number === 16);
    await db.commune.insertMany([
      { name: "Bulnes", regionId: reg16._id },
      { name: "Chillán Viejo", regionId: reg16._id },
      { name: "Chillán", regionId: reg16._id },
      { name: "Cobquecura", regionId: reg16._id },
      { name: "Coelemu", regionId: reg16._id },
      { name: "Coihueco", regionId: reg16._id },
      { name: "El Carmen", regionId: reg16._id },
      { name: "Ninhue", regionId: reg16._id },
      { name: "Ñiquén", regionId: reg16._id },
      { name: "Pemuco", regionId: reg16._id },
      { name: "Pinto", regionId: reg16._id },
      { name: "Portezuelo", regionId: reg16._id },
      { name: "Quillón", regionId: reg16._id },
      { name: "Quirihue", regionId: reg16._id },
      { name: "Ránquil", regionId: reg16._id },
      { name: "San Carlos", regionId: reg16._id },
      { name: "San Fabián", regionId: reg16._id },
      { name: "San Ignacio", regionId: reg16._id },
      { name: "San Nicolás", regionId: reg16._id },
      { name: "Treguaco", regionId: reg16._id },
      { name: "Yungay", regionId: reg16._id },
    ]);
    const reg8 = storedRegions.find((r) => r.number === 8);
    await db.commune.insertMany([
      { name: "Alto Biobío", regionId: reg8._id },
      { name: "Antuco", regionId: reg8._id },
      { name: "Arauco", regionId: reg8._id },
      { name: "Cabrero", regionId: reg8._id },
      { name: "Cañete", regionId: reg8._id },
      { name: "Chiguayante", regionId: reg8._id },
      { name: "Concepción", regionId: reg8._id },
      { name: "Contulmo", regionId: reg8._id },
      { name: "Coronel", regionId: reg8._id },
      { name: "Curanilahue", regionId: reg8._id },
      { name: "Florida", regionId: reg8._id },
      { name: "Hualpén", regionId: reg8._id },
      { name: "Hualqui", regionId: reg8._id },
      { name: "Laja", regionId: reg8._id },
      { name: "Lebu", regionId: reg8._id },
      { name: "Los Álamos", regionId: reg8._id },
      { name: "Los Ángeles", regionId: reg8._id },
      { name: "Lota", regionId: reg8._id },
      { name: "Mulchén", regionId: reg8._id },
      { name: "Nacimiento", regionId: reg8._id },
      { name: "Negrete", regionId: reg8._id },
      { name: "Penco", regionId: reg8._id },
      { name: "Quilaco", regionId: reg8._id },
      { name: "Quilleco", regionId: reg8._id },
      { name: "San Pedro de la Paz", regionId: reg8._id },
      { name: "San Rosendo", regionId: reg8._id },
      { name: "Santa Bárbara", regionId: reg8._id },
      { name: "Santa Juana", regionId: reg8._id },
      { name: "Talcahuano", regionId: reg8._id },
      { name: "Tirúa", regionId: reg8._id },
      { name: "Tomé", regionId: reg8._id },
      { name: "Tucapel", regionId: reg8._id },
      { name: "Yumbel", regionId: reg8._id },
    ]);
    const reg9 = storedRegions.find((r) => r.number === 9);
    await db.commune.insertMany([
      { name: "Angol", regionId: reg9._id },
      { name: "Carahue", regionId: reg9._id },
      { name: "Cholchol", regionId: reg9._id },
      { name: "Collipulli", regionId: reg9._id },
      { name: "Cunco", regionId: reg9._id },
      { name: "Curacautín", regionId: reg9._id },
      { name: "Curarrehue", regionId: reg9._id },
      { name: "Ercilla", regionId: reg9._id },
      { name: "Freire", regionId: reg9._id },
      { name: "Galvarino", regionId: reg9._id },
      { name: "Gorbea", regionId: reg9._id },
      { name: "Lautaro", regionId: reg9._id },
      { name: "Loncoche", regionId: reg9._id },
      { name: "Lonquimay", regionId: reg9._id },
      { name: "Los Sauces", regionId: reg9._id },
      { name: "Lumaco", regionId: reg9._id },
      { name: "Melipeuco", regionId: reg9._id },
      { name: "Nueva Imperial", regionId: reg9._id },
      { name: "Padre las Casas", regionId: reg9._id },
      { name: "Perquenco", regionId: reg9._id },
      { name: "Pitrufquén", regionId: reg9._id },
      { name: "Pucón", regionId: reg9._id },
      { name: "Purén", regionId: reg9._id },
      { name: "Renaico", regionId: reg9._id },
      { name: "Saavedra", regionId: reg9._id },
      { name: "Temuco", regionId: reg9._id },
      { name: "Teodoro Schmidt", regionId: reg9._id },
      { name: "Toltén", regionId: reg9._id },
      { name: "Traiguén", regionId: reg9._id },
      { name: "Victoria", regionId: reg9._id },
      { name: "Vilcún", regionId: reg9._id },
      { name: "Villarrica", regionId: reg9._id },
    ]);
    const reg14 = storedRegions.find((r) => r.number === 14);
    await db.commune.insertMany([
      { name: "Corral", regionId: reg14._id },
      { name: "Futrono", regionId: reg14._id },
      { name: "La Unión", regionId: reg14._id },
      { name: "Lago Ranco", regionId: reg14._id },
      { name: "Lanco", regionId: reg14._id },
      { name: "Los Lagos", regionId: reg14._id },
      { name: "Mariquina", regionId: reg14._id },
      { name: "Máfil", regionId: reg14._id },
      { name: "Paillaco", regionId: reg14._id },
      { name: "Panguipulli", regionId: reg14._id },
      { name: "Río Bueno", regionId: reg14._id },
      { name: "Valdivia", regionId: reg14._id },
    ]);
    const reg10 = storedRegions.find((r) => r.number === 10);
    await db.commune.insertMany([
      { name: "Ancud", regionId: reg10._id },
      { name: "Calbuco", regionId: reg10._id },
      { name: "Castro", regionId: reg10._id },
      { name: "Chaitén", regionId: reg10._id },
      { name: "Chonchi", regionId: reg10._id },
      { name: "Cochamó", regionId: reg10._id },
      { name: "Curaco de Vélez", regionId: reg10._id },
      { name: "Dalcahue", regionId: reg10._id },
      { name: "Fresia", regionId: reg10._id },
      { name: "Frutillar", regionId: reg10._id },
      { name: "Futaleufú", regionId: reg10._id },
      { name: "Hualaihué", regionId: reg10._id },
      { name: "Llanquihue", regionId: reg10._id },
      { name: "Los Muermos", regionId: reg10._id },
      { name: "Maullín", regionId: reg10._id },
      { name: "Osorno", regionId: reg10._id },
      { name: "Palena", regionId: reg10._id },
      { name: "Puerto Montt", regionId: reg10._id },
      { name: "Puerto Octay", regionId: reg10._id },
      { name: "Puerto Varas", regionId: reg10._id },
      { name: "Puqueldón", regionId: reg10._id },
      { name: "Purranque", regionId: reg10._id },
      { name: "Puyehue", regionId: reg10._id },
      { name: "Queilén", regionId: reg10._id },
      { name: "Quellón", regionId: reg10._id },
      { name: "Quemchi", regionId: reg10._id },
      { name: "Quinchao", regionId: reg10._id },
      { name: "Río Negro", regionId: reg10._id },
      { name: "San Juan de la Costa", regionId: reg10._id },
      { name: "San Pablo", regionId: reg10._id },
    ]);
    const reg11 = storedRegions.find((r) => r.number === 11);
    await db.commune.insertMany([
      { name: "Aisén", regionId: reg11._id },
      { name: "Chile Chico", regionId: reg11._id },
      { name: "Cisnes", regionId: reg11._id },
      { name: "Cochrane", regionId: reg11._id },
      { name: "Coyhaique", regionId: reg11._id },
      { name: "Guaitecas", regionId: reg11._id },
      { name: "Lago Verde", regionId: reg11._id },
      { name: "O’Higgins", regionId: reg11._id },
      { name: "Río Ibáñez", regionId: reg11._id },
      { name: "Tortel", regionId: reg11._id },
    ]);
    const reg12 = storedRegions.find((r) => r.number === 12);
    await db.commune.insertMany([
      { name: "Antártica", regionId: reg12._id },
      { name: "Cabo de Hornos (Ex Navarino)", regionId: reg12._id },
      { name: "Laguna Blanca", regionId: reg12._id },
      { name: "Natales", regionId: reg12._id },
      { name: "Porvenir", regionId: reg12._id },
      { name: "Primavera", regionId: reg12._id },
      { name: "Punta Arenas", regionId: reg12._id },
      { name: "Río Verde", regionId: reg12._id },
      { name: "San Gregorio", regionId: reg12._id },
      { name: "Timaukel", regionId: reg12._id },
      { name: "Torres del Paine", regionId: reg12._id },
    ]);
  }
};

module.exports = init;
